Student: Duncan Ferguson <br>
Student Id: 871641260 <br>
Class: Comp 4431-1 <br>
Assignment: Excercise 2 <br>
Date: 9/24/2021 <br>
Group: Name: Broken Toe <br>
Group Members: Emma Bright, Mike Santoro <br>

In [409]:
import numpy as np
import pandas as pd

In [410]:
locations = ['SouthGlenn','Tamarac','HighlandsRanch','ColoradoBlvd','WashingtonPark','CherryCreek',
             'GovernorsRanch','UnionStation','CastleRock']

itemCategories = ['produce', 'meat', 'bakery', 'freezer', 'dairy', 'deli', 'snack', 'softdrinks', 'beer', 'household']
numLocations = len(locations)
numItemCategories = len(itemCategories)

In [411]:
def getCatIndex(inCat):
    count = 0
    while (itemCategories[count] != inCat) and (count < len(itemCategories)-1):
        count += 1
    return (count)

def getlocIndex(inLoc):
    count = 0
    while (locations[count] != inCat) and (count < len(locations)-1):
        count += 1
    return(count)

def getMonth(inDate):
    return(int(inDate[5:7]))

In [412]:
# Creating Index Dictionary For the locations and items
location_dic = {locations[i]:i for i in range(0, numLocations)}
itemCategories_dic = {itemCategories[i]: i for i in range(0, numItemCategories)}

data = np.loadtxt("ds_ex3.txt", dtype='str')
df = pd.DataFrame(data, columns=["transactionid", "num_items_purchase",
                       "total_price","date", "store","category"])
df['date'] = df['date'].str[5:7]
df['date'] = pd.to_numeric(df['date'], downcast='integer')
df['store'] = df['store'].map(location_dic)
df['category'] = df['category'].map(itemCategories_dic)
df

transactionid num_items_purchase total_price  date  store  category
0                 0                  1        2.35    12      5         9
1                 1                 10       59.24     2      0         6
2                 1                  7       10.02     2      0         5
3                 1                 10       32.00     2      0         2
4                 1                  1        2.77     2      0         1
...             ...                ...         ...   ...    ...       ...
26154          9996                  4       23.36    10      4         0
26155          9997                  4       35.81     1      6         4
26156          9997                  2        9.20     1      6         7
26157          9998                  4       37.84     6      4         4
26158          9999                  2        8.71     4      2         9

[26159 rows x 6 columns]

In [413]:
# Creating a 3D numpy Array
cube = np.zeros((12, numLocations, numItemCategories, 2))
cube

array([[[[0., 0.],
         [0., 0.],
         [0., 0.],
         ...,
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         ...,
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         ...,
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        ...,

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         ...,
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         ...,
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         ...,
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         ...,
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         ...,
   

In [414]:
for index, row in df.iterrows():
    # cube[row.values[3]-1][row.index[4]][row.index[5]][0] += float(row.values[1])
    # cube[row.values[3]-1][row.index[4]][row.index[5]][1] += float(row.values[2])
    cube[row.values[3]-1][row.values[4]][row.values[5]][0] += float(row.values[1])
    # # cube[row.values[3]-1][row.values[4]][row.values[5]][1] += float(row.values[2])
print(cube[0])


[[[134.   0.]
  [ 77.   0.]
  [129.   0.]
  [206.   0.]
  [163.   0.]
  [157.   0.]
  [210.   0.]
  [215.   0.]
  [253.   0.]
  [ 79.   0.]]

 [[114.   0.]
  [ 65.   0.]
  [137.   0.]
  [ 82.   0.]
  [133.   0.]
  [118.   0.]
  [133.   0.]
  [ 72.   0.]
  [151.   0.]
  [ 44.   0.]]

 [[178.   0.]
  [142.   0.]
  [316.   0.]
  [204.   0.]
  [200.   0.]
  [236.   0.]
  [300.   0.]
  [280.   0.]
  [298.   0.]
  [ 76.   0.]]

 [[144.   0.]
  [ 61.   0.]
  [131.   0.]
  [122.   0.]
  [125.   0.]
  [133.   0.]
  [107.   0.]
  [ 89.   0.]
  [136.   0.]
  [ 47.   0.]]

 [[ 68.   0.]
  [ 39.   0.]
  [ 65.   0.]
  [ 88.   0.]
  [ 54.   0.]
  [ 89.   0.]
  [ 78.   0.]
  [ 91.   0.]
  [ 93.   0.]
  [ 27.   0.]]

 [[ 31.   0.]
  [ 22.   0.]
  [ 46.   0.]
  [ 36.   0.]
  [ 54.   0.]
  [ 37.   0.]
  [ 39.   0.]
  [ 49.   0.]
  [ 42.   0.]
  [ 21.   0.]]

 [[134.   0.]
  [ 65.   0.]
  [117.   0.]
  [ 77.   0.]
  [121.   0.]
  [ 96.   0.]
  [126.   0.]
  [110.   0.]
  [ 96.   0.]
  [ 37.   0.]]

 [[ 25

What to turn in:
-In the textbox write up what you found to be "interesting" in the data
-In the text box below the "interesting description, print out the contents of your Month vs ItemCategory 2D cub
- Attach Code

