Student: Duncan Ferguson <br>
Student Id: 871641260 <br>
Class: Comp 4431-1 <br>
Assignment: Excercise 2 <br>
Date: 9/24/2021 <br>
Group: Name: Broken Toe <br>
Group Members: Emma Bright, Mike Santoro <br>

In [456]:
import numpy as np
import pandas as pd

In [457]:
locations = ['SouthGlenn','Tamarac','HighlandsRanch','ColoradoBlvd','WashingtonPark','CherryCreek',
             'GovernorsRanch','UnionStation','CastleRock']
itemCategories = ['produce', 'meat', 'bakery', 'freezer', 'dairy', 'deli', 'snack', 'softdrinks',
                  'beer', 'household']
numLocations = len(locations)
numItemCategories = len(itemCategories)

# Creating Index Dictionary For the locations and items index's
location_dic = {locations[i]:i for i in range(0, numLocations)}
itemCategories_dic = {itemCategories[i]: i for i in range(0, numItemCategories)}

# Loading the data in as np array
data = np.loadtxt("ds_ex3.txt", dtype='str')

# Converting the np ara to a panda for manipulation
df = pd.DataFrame(data, columns=["transactionid", "num_items_purchase",
                       "total_price","date", "store","category"])
df['date'] = df['date'].str[5:7]
df['date'] = pd.to_numeric(df['date'], downcast='integer')
df['store'] = df['store'].map(location_dic)
df['category'] = df['category'].map(itemCategories_dic)
df

transactionid num_items_purchase total_price  date  store  category
0                 0                  1        2.35    12      5         9
1                 1                 10       59.24     2      0         6
2                 1                  7       10.02     2      0         5
3                 1                 10       32.00     2      0         2
4                 1                  1        2.77     2      0         1
...             ...                ...         ...   ...    ...       ...
26154          9996                  4       23.36    10      4         0
26155          9997                  4       35.81     1      6         4
26156          9997                  2        9.20     1      6         7
26157          9998                  4       37.84     6      4         4
26158          9999                  2        8.71     4      2         9

[26159 rows x 6 columns]

In [458]:
# Creating a 3D numpy Array
cube = np.zeros((12, numLocations, numItemCategories, 2))
cube

array([[[[0., 0.],
         [0., 0.],
         [0., 0.],
         ...,
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         ...,
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         ...,
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        ...,

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         ...,
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         ...,
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         ...,
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         ...,
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         ...,
   

In [459]:
for index, row in df.iterrows():
    # Month               # Store            # Category
    cube[row.values[3]-1][row.values[4]][row.values[5]][0] += float(row.values[1])  # Adding in Quantity
    cube[row.values[3]-1][row.values[4]][row.values[5]][1] += float(row.values[2])  # Adding in Total Price
cube[0]

array([[[ 134.  ,  224.96],
        [  77.  ,  585.96],
        [ 129.  ,  495.96],
        [ 206.  ,  764.61],
        [ 163.  ,  594.64],
        [ 157.  ,  659.65],
        [ 210.  ,  671.8 ],
        [ 215.  ,  652.36],
        [ 253.  ,  886.42],
        [  79.  ,  240.44]],

       [[ 114.  ,  285.47],
        [  65.  ,  674.84],
        [ 137.  ,  646.25],
        [  82.  ,  346.51],
        [ 133.  ,  662.77],
        [ 118.  ,  601.63],
        [ 133.  ,  573.66],
        [  72.  ,  351.29],
        [ 151.  , 1268.28],
        [  44.  ,  170.74]],

       [[ 178.  ,  436.66],
        [ 142.  , 1905.17],
        [ 316.  , 1851.68],
        [ 204.  , 1331.75],
        [ 200.  , 1066.79],
        [ 236.  , 1410.95],
        [ 300.  , 1855.59],
        [ 280.  , 1840.54],
        [ 298.  , 2846.96],
        [  76.  ,  387.62]],

       [[ 144.  ,  348.45],
        [  61.  ,  535.49],
        [ 131.  ,  707.95],
        [ 122.  ,  691.06],
        [ 125.  ,  539.95],
        [ 133.

In [460]:
numLocations_2d = np.zeros((12, numLocations, 2))
numItemCategories_2d = np.zeros((12, numItemCategories, 2))

np.shape(numLocations_2d)

(12, 9, 2)

In [461]:
# Getting 2d numItemCategories Shape
np.shape(numItemCategories_2d)

(12, 10, 2)

In [462]:
# 2D cube for looking at the locations. Just Taking the slice for the January to compare

for month in range(len(cube)):
    for loc in range(numLocations):
        temp = np.sum(cube[month][loc], axis=0)
        numLocations_2d[month][loc][0] += temp[0]
        numLocations_2d[month][loc][1] += temp[1]

numLocations_2d[0]






array([[ 1623.  ,  5776.8 ],
       [ 1049.  ,  5581.44],
       [ 2230.  , 14933.71],
       [ 1095.  ,  5738.21],
       [  692.  ,  5969.57],
       [  377.  ,  4111.61],
       [  979.  ,  5465.97],
       [  255.  ,  4023.76],
       [ 1174.  ,  4469.32]])