## Exercise 3: Data Cubes
### Team Name: Broken Toes
#### Team Members: Mike Santoro, Emma Bright, Duncan Ferguson
#### Submission By: Mike Santoro

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

You are to create and use data cubes using numpy arrays.  Your data set will be for whole foods purchases in Colorado.  The data will have 6 columns: transactionId, number items purchased, total price of those items, date, store, and category.
The functions below are given and will be used to extract data from the data-set.

In [2]:
# Takes inDate year.date.month
def getMonth(inDate):
    return(int(inDate[5:7]))

def getLocationIndex(inLoc):
    count = 0
    while (locations[count] != inLoc) and (count < len(locations)-1):
        count += 1
    return(count)

def getCatIndex(inCat):
    count = 0
    while (itemCategories[count] != inCat) and (count < len(itemCategories)-1):
        count += 1
    return(count)

In [3]:
columns = ["transactionId","number items purchased", "total price of those items", "date", "store","category"]

In [4]:
locations = ['SouthGlenn','Tamarac','HighlandsRanch','ColoradoBlvd','WashingtonPark','CherryCreek','GovernorsRanch','UnionStation','CastleRock']
numLocations = len(locations)
numLocations

9

In [5]:
itemCategories = ['produce','meat','bakery','freezer','dairy','deli','snack','softdrinks','beer','household']
numItemCategories = len(itemCategories)
numItemCategories

10

In [8]:
df = pd.read_csv('ds_ex3_csv.csv', names = columns)
df.head()

transactionId  number items purchased  total price of those items  \
0              0                       1                        2.35   
1              1                      10                       59.24   
2              1                       7                       10.02   
3              1                      10                       32.00   
4              1                       1                        2.77   

         date        store   category  
0  2019.12.13  CherryCreek  household  
1  2019.02.13   SouthGlenn      snack  
2  2019.02.13   SouthGlenn       deli  
3  2019.02.13   SouthGlenn     bakery  
4  2019.02.13   SouthGlenn       meat

In [9]:
df['month']=df.apply(lambda row: getMonth(row['date']),axis=1)
df['locationIndex']=df.apply(lambda row: getLocationIndex(row['store']),axis=1)
df['catIndex']=df.apply(lambda row: getCatIndex(row['category']),axis=1)

df.head()

transactionId  number items purchased  total price of those items  \
0              0                       1                        2.35   
1              1                      10                       59.24   
2              1                       7                       10.02   
3              1                      10                       32.00   
4              1                       1                        2.77   

         date        store   category  month  locationIndex  catIndex  
0  2019.12.13  CherryCreek  household     12              5         9  
1  2019.02.13   SouthGlenn      snack      2              0         6  
2  2019.02.13   SouthGlenn       deli      2              0         5  
3  2019.02.13   SouthGlenn     bakery      2              0         2  
4  2019.02.13   SouthGlenn       meat      2              0         1

*You are to create a two 3D base cubes using numpy arrays to hold the data.  The dimensions of the arrays are date, location, and category.  You can either create two cubes (one for NumberItems and the other for PriceItems) or one cube where each cell holds an object with both measures, whatever is easiest for you.*

The first part of this code block below creates the $(2)$ data-cubes. The second part populates the cube.

In [11]:
# creates a 3D numpy array
# where numLocations and numItemCategories are integers
cube_item = np.zeros((12,numLocations,numItemCategories))
cube_price = np.zeros((12,numLocations,numItemCategories))

#Fills the 
for index,row in df.iterrows():
    cube_item[row[6]-1, row[7], row[8]] += row[1]
    cube_price[row[6]-1, row[7], row[8]] += row[2]

In [12]:
print(f'Cube Price: {cube_price.shape}; Cube Item: {cube_item.shape}')
print()
print(cube_price)
print()
print(cube_item)

Cube Price: (12, 9, 10); Cube Item: (12, 9, 10)

[[[ 224.96  585.96  495.96 ...  652.36  886.42  240.44]
  [ 285.47  674.84  646.25 ...  351.29 1268.28  170.74]
  [ 436.66 1905.17 1851.68 ... 1840.54 2846.96  387.62]
  ...
  [ 297.1   778.04  743.72 ...  475.56  971.74  169.96]
  [ 177.76  570.01  296.8  ...  425.43  766.56  303.05]
  [ 280.84  516.8   603.89 ...  338.1   908.86  162.52]]

 [[ 175.27  460.02  740.35 ...  758.76 1181.    153.08]
  [ 217.75  511.21  579.5  ...  407.02  910.17   72.3 ]
  [ 762.95 1635.89 1240.93 ...  677.97 2447.04  338.43]
  ...
  [ 208.59  365.95  671.18 ...  439.63  873.73  111.02]
  [ 200.4   523.3   531.04 ...  295.52  586.85  286.3 ]
  [ 189.99  411.69  647.   ...  319.65  739.59   83.93]]

 [[ 329.03  514.71  744.42 ...  644.93 1044.66  210.14]
  [ 331.58  730.85  560.04 ...  668.28 1030.52  164.27]
  [ 781.58 1558.39  933.81 ...  999.34 1671.77  258.03]
  ...
  [ 264.84  583.91  361.59 ...  634.12  723.77  132.16]
  [ 300.19  901.96  354.25 ...  3

*After creating your base cube create three 2D cubes for the three attribute pairs.If you are using two base cubes, then create three 2D cubes for each base cube. Using your cubes (the 2D cubes will be very helpful), explore your data to see what is “interesting".*

In [ ]:
cat_loc_price = np.sum(cube_price, axis=0)
cat_loc_item = np.sum(cube_item, axis=0)

month_cat_price = np.sum(cube_price, axis=1)
month_cat_item = np.sum(cube_item, axis=1)

month_loc_price = np.sum(cube_price, axis=2)
month_loc_item = np.sum(cube_item, axis=2)

In [ ]:
print(f'Category vs Location Price shape: {cat_loc_price.shape}; Category vs Location Item shape: {cat_loc_item.shape}')
print()
print(f'Month vs Category Price shape: {month_cat_price.shape}; Month vs Category Item shape: {month_cat_item.shape}')
print()
print(f'Month vs Location Price shape: {month_loc_price.shape}; Month vs Category Item shape: {month_loc_item.shape}')

In [ ]:
months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

In [ ]:
month_cat_price_df = pd.DataFrame(month_cat_price, columns=itemCategories, index=months)
month_cat_item_df = pd.DataFrame(month_cat_item, columns=itemCategories, index=months)

month_loc_price_df = pd.DataFrame(month_loc_price, columns=locations, index=months)
month_loc_item_df = pd.DataFrame(month_loc_item, columns=locations, index=months)

cat_loc_price_df = pd.DataFrame(cat_loc_price, columns=itemCategories, index=locations)
cat_loc_item_df = pd.DataFrame(cat_loc_item, columns=itemCategories, index=locations)


Our thought was it would be able to be easier to draw insights from the data by using a heat map to represent the values
with colors so, we created heatmaps below.

In [ ]:
fig, axes = plt.subplots(3, 2, figsize=(18, 22))

fig.suptitle('Whole Foods Data Review')
fig.tight_layout(pad=10.0)

sns.heatmap(month_cat_price_df,ax=axes[0, 0],cmap='plasma')
sns.heatmap(month_cat_item_df,ax=axes[0, 1],cmap='plasma')
sns.heatmap(month_loc_price_df, ax=axes[1, 0],cmap='plasma')
sns.heatmap(month_loc_item_df, ax=axes[1, 1],cmap='plasma')
sns.heatmap(cat_loc_price_df, ax=axes[2, 0],cmap='plasma')
sns.heatmap(cat_loc_item_df, ax=axes[2, 1],cmap='plasma')
axes[0, 0].title.set_text('Month vs. Category Price')
axes[0, 1].title.set_text('Month vs. Category Item')
axes[1, 0].title.set_text('Month vs. Location Price')
axes[1, 1].title.set_text('Month vs. Location Item')
axes[2, 0].title.set_text('Category vs. Location Price')
axes[2, 1].title.set_text('Category vs. Location Item')

### Interesting Insights from the Data
-> From the Month vs. Category visual aides we find that Meat and Beer are strong during the summer months.

-> From the Month vs. Location visual aides we find that highlands ranch is our largest revenue generator through out the year and overall stores are busier based on sales and products sold in the summer months.

-> From the Category vs. Location visual aides we find that highlands ranch sells the most beer and at a high price. It is interesting to find that both CastleRock and SouthGlenn sell more less expensive beer.