Student: Duncan Ferguson <br>
Student Id: 871641260 <br>
Class: Comp 4431-1 <br>
Assignment: Assignment 2 <br>
Date: 11/12/2021 <br>
*Project was Completed by Individual, group is just listed below for reference to past code that might
be reused from previous Excercises* <br>
Group: Name: Broken Toe <br>
Group Members: Emma Bright, Mike Santoro <br>

### Assignment Description:
In this assignment you are to use Decision trees and Naive Bayes for classification. In addition, you are to explore
 your models to determine which feature vector attributes you can remove without "significantly hurting"
 classification importance. There is no single "right" answer for this question. Also, "significantly hurting"
 is a judgement call, please explain why you mean by that and provided numeric values. You should start with
 the full dataset and look at the decision tree features_importances_ and naive bayes permutation_importance
 to guid which attributes to remove. You will then want to iteratively remove attributes, possibly one at a time or
 several at a time. Again, there is no single "right way" to do this.

The goal is to predict whether it will rain tomorrow given the days weather statistics. The last column,
"Rain Tomorrow" is the classification value for I have cleaned the data set for you. I removed a few attributes that
were almost all zeros, and replaced missing values with the mean value for that column. Also, strings have been
transformed into numeric values so the data set will work well for both decision trees and naive bayes. <br>

#### What To Turn In: <br>
1). A report that explains which attributes you have eliminated, why those, and what effect this has on the quality of
predictions compared to using the full dataset. Feel free to include a table of feature_importances and
 permutation_importances that show how any why you reduced the set of attributes. <br>

2). Your code for creating the decision tree and naive bayes models and getting the feature/permuttion importances.
Your code does not need to cover your whole experimental space, but should provide enough information to show how you
made at least one decision about which attribute (column) to eliminate


In [646]:
# Importing main python packages for assignment
import numpy as np
import pandas as pd
from sklearn import tree
from sklearn.naive_bayes import *
from sklearn.model_selection import train_test_split
from sklearn.metrics import *
from sklearn.inspection import permutation_importance

In [647]:
def train_data(df, drops=None):
    """This function trains the data and returns the desired drops"""
    # Y is the classification
    Y = df['RainTomorrow'].tolist()
    X = df.copy()
    X = X.drop(columns=["RainTomorrow"])
    if drops != None:
        X = X.drop(columns=drops)
    x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.25, random_state=42)
    return x_train, x_test, y_train, y_test, X

In [648]:
def decisionTree_Model(x_train, x_test, y_train, y_test, X):
    """This Function Goes through and prints out the Decision tree model"""
    # Building out a decision tree
    dtree = tree.DecisionTreeClassifier(criterion="gini")
    dtree = dtree.fit(x_train, y_train)
    y_predicted = dtree.predict(x_test)
    accuracy = accuracy_score(y_test, y_predicted)
    print("DecisionTree Accuracy: ", accuracy)
    print("DecisionTree Confusion Matrix:")
    print(confusion_matrix(y_test, y_predicted))
    important = dtree.feature_importances_
    df_importance_list = []
    for i, v in enumerate(important):
        df_importance_list.append([X.columns[i], v])
    df_importance = pd.DataFrame(df_importance_list, columns=["FName", "Score"])
    df_importance.sort_values(by=['Score'], ascending=False, inplace=True)
    print("decision tree dtree feature importance:")
    print(df_importance)
    decisionTree_Model_Features = df_importance["FName"].tolist()
    return accuracy, decisionTree_Model_Features

def decisionTree_Model_NP(x_train, x_test, y_train, y_test, X):
    """This Function Goes through and prints out the Decision tree model without the print functions"""
    # Building out a decision tree
    dtree = tree.DecisionTreeClassifier(criterion="gini")
    dtree = dtree.fit(x_train, y_train)
    y_predicted = dtree.predict(x_test)
    accuracy = accuracy_score(y_test, y_predicted)
    important = dtree.feature_importances_
    df_importance_list = []
    for i, v in enumerate(important):
        df_importance_list.append([X.columns[i], v])
    df_importance = pd.DataFrame(df_importance_list, columns=["FName", "Score"])
    df_importance.sort_values(by=['Score'], ascending=False, inplace=True)
    decisionTree_Model_Features = df_importance["FName"].tolist()
    return accuracy, decisionTree_Model_Features


In [649]:
def GausianNB_Model(x_train, x_test, y_train, y_test, X):
    """This Function takes in the training and the testing models to help create the GausianNB Model"""
    model2 = GaussianNB()
    model2.fit(x_train, y_train)
    gausianNB_predicted = model2.predict(x_test)
    print('\nconfusion_matrix from Gaussian naive bayes:')
    print(confusion_matrix( y_test, gausianNB_predicted ) )
    accuracy = accuracy_score(y_test, gausianNB_predicted)
    print('accuracy = ' + str(accuracy))
    imps = permutation_importance(model2, x_test, y_test)
    print("gausianNB feature importance:")
    df_Gausian_Feature_Importance_List = []
    Gausian_Feature_Importance_List =  imps.importances_mean.tolist()
    for row in enumerate(Gausian_Feature_Importance_List):
        df_Gausian_Feature_Importance_List.append([X.columns[row[0]], row[1]])
    df_Gausian_Feature_Importance = pd.DataFrame(df_Gausian_Feature_Importance_List, columns=["Feature", "Significance"])
    df_Gausian_Feature_Importance.sort_values(by=["Significance"], ascending=False, inplace=True)
    GausianND_Features = df_Gausian_Feature_Importance["Feature"].tolist()
    print(GausianND_Features)
    print(df_Gausian_Feature_Importance)
    return accuracy, GausianND_Features

def GausianNB_Model_NP(x_train, x_test, y_train, y_test, X):
    """This Function takes in the training and the testing models to help create the GausianNB Model
    but does not print off any responses"""
    model2 = GaussianNB()
    model2.fit(x_train, y_train)
    gausianNB_predicted = model2.predict(x_test)
    accuracy = accuracy_score(y_test, gausianNB_predicted)
    imps = permutation_importance(model2, x_test, y_test)
    df_Gausian_Feature_Importance_List = []
    Gausian_Feature_Importance_List =  imps.importances_mean.tolist()
    for row in enumerate(Gausian_Feature_Importance_List):
        df_Gausian_Feature_Importance_List.append([X.columns[row[0]], row[1]])
    df_Gausian_Feature_Importance = pd.DataFrame(df_Gausian_Feature_Importance_List, columns=["Feature", "Significance"])
    df_Gausian_Feature_Importance.sort_values(by=["Significance"], ascending=False, inplace=True)
    GausianND_Features = df_Gausian_Feature_Importance["Feature"].tolist()
    return accuracy, GausianND_Features


In [650]:
# np.random.seed(10)
# Importing data
df = pd.read_csv("assignment2_cleanInfile.csv")
x_train, x_test, y_train, y_test, X = train_data(df)

In [651]:
d1 = decisionTree_Model(x_train, x_test, y_train, y_test, X)

DecisionTree Accuracy:  0.78466342231849
DecisionTree Confusion Matrix:
[[23603  4020]
 [ 3635  4291]]
decision tree dtree feature importance:
            FName     Score
11    Humidity3pm  0.269838
13    Pressure3pm  0.072038
3        Rainfall  0.063650
5   WindGustSpeed  0.061403
1         MinTemp  0.049930
10    Humidity9am  0.049629
12    Pressure9am  0.046478
17        Temp3pm  0.046383
16        Temp9am  0.045483
2         MaxTemp  0.040349
0        Location  0.038276
9    WindSpeed3pm  0.037075
8    WindSpeed9am  0.033342
7      WindDir3pm  0.031974
4     WindGustDir  0.030970
15       Cloud3pm  0.029977
6      WindDir9am  0.029319
14       Cloud9am  0.020898
18      RainToday  0.002987


In [652]:
g1 = GausianNB_Model(x_train, x_test, y_train, y_test, X)


confusion_matrix from Gaussian naive bayes:
[[24213  3410]
 [ 3488  4438]]
accuracy = 0.8059579735013643
gausianNB feature importance:
['Humidity3pm', 'Rainfall', 'Pressure3pm', 'WindGustSpeed', 'Pressure9am', 'Cloud3pm', 'MinTemp', 'Cloud9am', 'Location', 'WindSpeed3pm', 'WindGustDir', 'Humidity9am', 'WindDir3pm', 'Temp9am', 'WindSpeed9am', 'WindDir9am', 'Temp3pm', 'MaxTemp', 'RainToday']
          Feature  Significance
11    Humidity3pm      0.014650
3        Rainfall      0.014003
13    Pressure3pm      0.004962
5   WindGustSpeed      0.004467
12    Pressure9am      0.003668
15       Cloud3pm      0.002582
1         MinTemp      0.001435
14       Cloud9am      0.000158
0        Location     -0.000090
9    WindSpeed3pm     -0.000428
4     WindGustDir     -0.000444
10    Humidity9am     -0.000467
7      WindDir3pm     -0.000518
16        Temp9am     -0.000540
8    WindSpeed9am     -0.000551
6      WindDir9am     -0.000866
17        Temp3pm     -0.001063
2         MaxTemp     -0.00138

Looking at the first model assumptions we can definitely conclude that the Humidity3pm column is the most important
for determining a significance. But there are a few more ways to go through this. The example below will show the
new models when dropping "RainToday" which has the least significance on the decisionTree Model

In [653]:
x_train, x_test, y_train, y_test, X = train_data(df, ["RainToday"])
d2 = decisionTree_Model(x_train, x_test, y_train, y_test, X)

DecisionTree Accuracy:  0.7838195167233959
DecisionTree Confusion Matrix:
[[23620  4003]
 [ 3682  4244]]
decision tree dtree feature importance:
            FName     Score
11    Humidity3pm  0.269728
13    Pressure3pm  0.072389
3        Rainfall  0.063903
5   WindGustSpeed  0.059412
1         MinTemp  0.051024
10    Humidity9am  0.050363
12    Pressure9am  0.048029
16        Temp9am  0.046947
17        Temp3pm  0.045102
0        Location  0.040691
2         MaxTemp  0.039389
9    WindSpeed3pm  0.037540
8    WindSpeed9am  0.034148
7      WindDir3pm  0.031926
4     WindGustDir  0.030624
15       Cloud3pm  0.029738
6      WindDir9am  0.027597
14       Cloud9am  0.021451


In [654]:
g2 = GausianNB_Model(x_train, x_test, y_train, y_test, X)


confusion_matrix from Gaussian naive bayes:
[[24720  2903]
 [ 3617  4309]]
accuracy = 0.8165911839995499
gausianNB feature importance:
['Humidity3pm', 'Rainfall', 'Pressure3pm', 'WindGustSpeed', 'Pressure9am', 'Cloud3pm', 'Humidity9am', 'MinTemp', 'Cloud9am', 'Location', 'WindGustDir', 'Temp9am', 'WindDir9am', 'WindSpeed3pm', 'WindDir3pm', 'WindSpeed9am', 'Temp3pm', 'MaxTemp']
          Feature  Significance
11    Humidity3pm      0.022290
3        Rainfall      0.017401
13    Pressure3pm      0.005446
5   WindGustSpeed      0.005390
12    Pressure9am      0.004270
15       Cloud3pm      0.003781
10    Humidity9am      0.003561
1         MinTemp      0.002481
14       Cloud9am      0.000141
0        Location     -0.000174
4     WindGustDir     -0.000371
16        Temp9am     -0.000416
6      WindDir9am     -0.000557
9    WindSpeed3pm     -0.000641
7      WindDir3pm     -0.000810
8    WindSpeed9am     -0.000878
17        Temp3pm     -0.000940
2         MaxTemp     -0.001553


Interestingly enough. When we drop the Rain Today the decision tree model accuracy model goes down.
Where as Gausiann model accuracy goes up.
Decision Tree Accuracy 0.7823567470252327 -> 0.7802751132240007
Gaussian Accuracy 0.807111311147993 -> 0.8174350895946441

Let's first look at the decision tree and go with a forward select. From our first two run's obviously Humidity3pm
has the most significance. So We'll keep that then add the next category that bumps up the value


In [655]:
def backward_selection(accuracy, features, selection, df, model):
    """This is a forward selection model"""
    # print("Starting Accuracy", accuracy, "Drop Feature", selection)
    features_loop = [word for word in features if word not in selection]
    drop_feature = ["None"]
    for feature in features_loop:
        x_train, x_test, y_train, y_test, X = train_data(df, feature)
        if model == 1:  # 1 For decisionTree
            new_accuracy, new_features = decisionTree_Model_NP(x_train, x_test, y_train, y_test, X)
        else:
            new_accuracy, new_features = GausianNB_Model_NP(x_train, x_test, y_train, y_test, X)
        # print(new_accuracy, "<new accuracy", feature," accuracy>",accuracy)
        if new_accuracy >= accuracy:
            accuracy = new_accuracy
            drop_feature = feature
            # print(new_accuracy, drop_feature)
    print("Accuracy:", accuracy, "\nFeatures:", new_features,"\nDropped Feature:", drop_feature)
    return accuracy, drop_feature, new_features

In [656]:
features = df.columns.tolist()
features.pop(-1)
accuracy = 0
selection = []
na1, drop1, new_features1 = backward_selection(accuracy, features, selection, df, 1)

Accuracy: 0.7882640861908915 
Features: ['Humidity3pm', 'Pressure3pm', 'Rainfall', 'WindGustSpeed', 'MinTemp', 'Humidity9am', 'Temp9am', 'Temp3pm', 'Pressure9am', 'Location', 'MaxTemp', 'WindSpeed3pm', 'WindSpeed9am', 'WindGustDir', 'WindDir3pm', 'Cloud3pm', 'WindDir9am', 'Cloud9am'] 
Dropped Feature: Cloud3pm


In [657]:
na2, drop2, new_features2 = backward_selection(na1, features, drop1, df, 1)


Accuracy: 0.7882640861908915 
Features: ['Humidity3pm', 'Pressure3pm', 'Rainfall', 'WindGustSpeed', 'MinTemp', 'Humidity9am', 'Temp9am', 'Pressure9am', 'Temp3pm', 'Location', 'MaxTemp', 'WindSpeed3pm', 'WindSpeed9am', 'WindDir3pm', 'WindGustDir', 'Cloud3pm', 'WindDir9am', 'Cloud9am'] 
Dropped Feature: ['None']


Looking at the backward selection model , we do not loose to many features before we hit the optimum selection model

Now looking at backward_selection model with the gausian

In [658]:
gna1, gb_drop1, gb_feature = backward_selection(accuracy, features, selection, df, 0)

Accuracy: 0.8165911839995499 
Features: ['Humidity3pm', 'Rainfall', 'WindGustSpeed', 'Pressure3pm', 'Pressure9am', 'Cloud3pm', 'Humidity9am', 'MinTemp', 'Cloud9am', 'Location', 'Temp9am', 'WindGustDir', 'WindDir3pm', 'WindDir9am', 'WindSpeed3pm', 'Temp3pm', 'WindSpeed9am', 'MaxTemp'] 
Dropped Feature: RainToday


In [659]:
gna2, gb_drop2, gb_feature2 = backward_selection(gna1, features, gb_drop1, df, 0)

Accuracy: 0.8165911839995499 
Features: ['Humidity3pm', 'Rainfall', 'WindGustSpeed', 'Pressure3pm', 'Cloud3pm', 'Pressure9am', 'MinTemp', 'Humidity9am', 'Cloud9am', 'Location', 'Temp9am', 'WindGustDir', 'WindDir3pm', 'MaxTemp', 'WindDir9am', 'WindSpeed3pm', 'WindSpeed9am', 'RainToday'] 
Dropped Feature: ['None']


It's interesting to see that both the gausian model and the decision tree only dropped one value
during the backward selection model. Dropping more features did not improve the model. To dive into
this a bit further I will now look into the forward model selection

In [660]:
def forward_selection(accuracy, features, selection, df, model):
    """This is a forward selection model"""
    for feature in features:
        droplist = [word for word in features if word not in [selection]+[feature]]
        # print([feature] + [selection])
        x_train, x_test, y_train, y_test, X = train_data(df, droplist)
        if model == 1:  # 1 For decisionTree
            new_accuracy, new_features = decisionTree_Model_NP(x_train, x_test, y_train, y_test, X)
        else:
            new_accuracy, new_features = GausianNB_Model_NP(x_train, x_test, y_train, y_test, X)
        if new_accuracy >= accuracy:
            accuracy = new_accuracy
            added_feature = feature
    print("Accuracy: ", accuracy, "Added Feature: ", added_feature, "All Features: ", new_features)
    return accuracy, added_feature, new_features

In [661]:
features = df.columns.tolist()
features.pop(-1)
accuracy = 0
selection = []
na1, add1, new_features1 = forward_selection(accuracy, features, selection, df, 1)

Accuracy:  0.8219921798081521 Added Feature:  Humidity3pm All Features:  ['RainToday']


In [662]:
na2, add2,new_features2 = forward_selection(na1, features, new_features1, df, 1)

Accuracy:  0.8219921798081521 Added Feature:  Humidity3pm All Features:  ['RainToday']


Once again we only have one feature that was selected to the model as the predictor in the decision tree.
Surprisingly this one feature has been the best predictor of any of the models.

In [663]:
na1, add1, new_features1 = forward_selection(accuracy, features, selection, df, 0)

Accuracy:  0.8205012799234859 Added Feature:  Humidity3pm All Features:  ['RainToday']


In [664]:
na2, add2,new_features2 = forward_selection(na1, features, new_features1, df, 0)

Accuracy:  0.8205012799234859 Added Feature:  Humidity3pm All Features:  ['RainToday']


Going back through to give this a little bit more of a look to see if we can manually bump these numbers

In [665]:
x_train, x_test, y_train, y_test, X = train_data(df, ["WindGustDir", "WindDir3pm", "WindDir9am","Temp3pm", "WindSpeed9am", "WindSpeed3pm", "MaxTemp"])


d2 = decisionTree_Model(x_train, x_test, y_train, y_test, X)

DecisionTree Accuracy:  0.7809221075135728
DecisionTree Confusion Matrix:
[[23532  4091]
 [ 3697  4229]]
decision tree dtree feature importance:
            FName     Score
5     Humidity3pm  0.285323
7     Pressure3pm  0.098820
1         MinTemp  0.089465
10        Temp9am  0.086268
3   WindGustSpeed  0.081084
6     Pressure9am  0.077986
4     Humidity9am  0.076111
2        Rainfall  0.076007
0        Location  0.056442
9        Cloud3pm  0.038861
8        Cloud9am  0.029434
11      RainToday  0.004199


In [666]:
g2 = GausianNB_Model(x_train, x_test, y_train, y_test, X)



confusion_matrix from Gaussian naive bayes:
[[24579  3044]
 [ 3653  4273]]
accuracy = 0.8116121409884948
gausianNB feature importance:
['Humidity3pm', 'Rainfall', 'WindGustSpeed', 'Cloud3pm', 'Pressure3pm', 'Pressure9am', 'Humidity9am', 'Cloud9am', 'MinTemp', 'Location', 'Temp9am', 'RainToday']
          Feature  Significance
5     Humidity3pm      0.017418
2        Rainfall      0.012827
3   WindGustSpeed      0.006746
9        Cloud3pm      0.003522
7     Pressure3pm      0.002599
6     Pressure9am      0.001710
4     Humidity9am      0.000591
8        Cloud9am      0.000124
1         MinTemp     -0.000039
0        Location     -0.000113
10        Temp9am     -0.000191
11      RainToday     -0.001575
